ALTER TABLE users
    ADD COLUMN pode_aprovar BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN pode_exportar BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN pode_ver_dashboard BOOLEAN NOT NULL DEFAULT FALSE;